version: "3.3"

services:
  postgres:
    container_name: postgres-farmacia
    image: postgres:13
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data/postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin-farmacia
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
